export const RESERVATION_GUIDE_URL = 'https://backreservas.ucompensar.edu.co/docs/Instructivo_Reservas_Coworking.pdf';

const FLOOR_MAPS_BASE_URL = 'https://backreservas.ucompensar.edu.co/img/floors';
const getFloorMapUrl = (fileName) => `${FLOOR_MAPS_BASE_URL}/${encodeURIComponent(fileName)}`;

export const TEUSAQUILLO_COWORKING_MAPS = [
    {
        id: 'tsq-i-p2',
        shortLabel: 'Bloque I - Piso 2',
        title: 'Bloque I - Piso 2',
        imageUrl: getFloorMapUrl('Sede I-Segundo Piso.png'),
        fallbackImageUrl: 'https://backreservas.ucompensar.edu.co/img/tsq_i_p2.png',
        alt: 'Plano del bloque I piso 2 del Campus Teusaquillo',
        summary: 'Distribuci\u00f3n de coworking para TI, Core Acad\u00e9mico y Planeaci\u00f3n.',
        details: [
            {
                label: 'Coworking - TI + Core Acad\u00e9mico',
                meta: '32 puestos',
                color: '#38d4c7',
            },
            {
                label: 'Coworking - Planeaci\u00f3n',
                color: '#ffd15a',
            },
            {
                label: 'Sala de reunion',
                color: '#b45589',
            },
        ],
    },
    {
        id: 'tsq-j-p1',
        shortLabel: 'Bloque J - Piso 1',
        title: 'Bloque J - Piso 1',
        imageUrl: getFloorMapUrl('Sede J-Primer Piso.png'),
        alt: 'Plano del bloque J piso 1 del Campus Teusaquillo',
        summary: 'Ubicaci\u00f3n del coworking de Vicerrector\u00eda Desarrollo Empresarial y Experiencia Cliente.',
        details: [
            {
                label: 'Coworking - Vicerrector\u00eda Desarrollo Empresarial y Experiencia Cliente',
                meta: '20 puestos',
                color: '#38d4c7',
            },
            {
                label: 'Sala de reunion',
                color: '#b45589',
            },
        ],
    },
    {
        id: 'tsq-i-p1',
        shortLabel: 'Bloque I - Piso 1',
        title: 'Bloque I - Piso 1',
        imageUrl: getFloorMapUrl('Sede I-Primer Piso.png'),
        alt: 'Plano del bloque I piso 1 del Campus Teusaquillo',
        summary: 'Ubicaci\u00f3n del coworking de Tesorer\u00eda, Compras, Planeaci\u00f3n Financiera y Contabilidad.',
        details: [
            {
                label: 'Coworking - Tesorer\u00eda - Compras - Planeaci\u00f3n Financiera - Contabilidad',
                meta: '18 puestos',
                color: '#38d4c7',
            },
            {
                label: 'Sala de reunion',
                color: '#b45589',
            },
        ],
    },
    {
        id: 'tsq-h-p1',
        shortLabel: 'Bloque H - Piso 1',
        title: 'Bloque H - Piso 1',
        imageUrl: getFloorMapUrl('Sede H-Primer Piso.png'),
        alt: 'Plano del bloque H piso 1 del Campus Teusaquillo',
        summary: 'Plano de distribuci\u00f3n del bloque H, primer piso.',
        details: [],
    },
    {
        id: 'tsq-f-p3',
        shortLabel: 'Bloque F - Piso 3',
        title: 'Bloque F - Piso 3',
        imageUrl: getFloorMapUrl('Sede F-Tercer Piso.png'),
        alt: 'Plano del bloque F piso 3 del Campus Teusaquillo',
        summary: 'Plano de distribuci\u00f3n del bloque F, tercer piso.',
        details: [],
    },
    {
        id: 'tsq-f-p2',
        shortLabel: 'Bloque F - Piso 2',
        title: 'Bloque F - Piso 2',
        imageUrl: getFloorMapUrl('Sede F-Segundo Piso.png'),
        alt: 'Plano del bloque F piso 2 del Campus Teusaquillo',
        summary: 'Plano de distribuci\u00f3n del bloque F, segundo piso.',
        details: [],
    },
    {
        id: 'tsq-f-p1',
        shortLabel: 'Bloque F - Piso 1',
        title: 'Bloque F - Piso 1',
        imageUrl: getFloorMapUrl('Sede F-Primer Piso.png'),
        alt: 'Plano del bloque F piso 1 del Campus Teusaquillo',
        summary: 'Plano de distribuci\u00f3n del bloque F, primer piso.',
        details: [],
    },
    {
        id: 'tsq-e-p2',
        shortLabel: 'Bloque E - Piso 2',
        title: 'Bloque E - Piso 2',
        imageUrl: getFloorMapUrl('Sede E-Segundo Piso.png'),
        alt: 'Plano del bloque E piso 2 del Campus Teusaquillo',
        summary: 'Plano de distribuci\u00f3n del bloque E, segundo piso.',
        details: [],
    },
    {
        id: 'tsq-d-p1',
        shortLabel: 'Bloque D - Piso 1',
        title: 'Bloque D - Piso 1',
        imageUrl: getFloorMapUrl('Sede D-Primer Piso.png'),
        alt: 'Plano del bloque D piso 1 del Campus Teusaquillo',
        summary: 'Plano de distribuci\u00f3n del bloque D, primer piso.',
        details: [],
    },
    {
        id: 'tsq-c-p1',
        shortLabel: 'Bloque C - Piso 1',
        title: 'Bloque C - Piso 1',
        imageUrl: getFloorMapUrl('Sede C-Primer Piso.png'),
        alt: 'Plano del bloque C piso 1 del Campus Teusaquillo',
        summary: 'Plano de distribuci\u00f3n del bloque C, primer piso.',
        details: [],
    },
    {
        id: 'tsq-b-p2',
        shortLabel: 'Bloque B - Piso 2',
        title: 'Bloque B - Piso 2',
        imageUrl: getFloorMapUrl('Sede B-Segundo Piso.png'),
        alt: 'Plano del bloque B piso 2 del Campus Teusaquillo',
        summary: 'Plano de distribuci\u00f3n del bloque B, segundo piso.',
        details: [],
    },
    {
        id: 'tsq-b-p1',
        shortLabel: 'Bloque B - Piso 1',
        title: 'Bloque B - Piso 1',
        imageUrl: getFloorMapUrl('Sede B-Primer Piso.png'),
        alt: 'Plano del bloque B piso 1 del Campus Teusaquillo',
        summary: 'Plano de distribuci\u00f3n del bloque B, primer piso.',
        details: [],
    },
    {
        id: 'tsq-a-p3',
        shortLabel: 'Bloque A - Piso 3',
        title: 'Bloque A - Piso 3',
        imageUrl: getFloorMapUrl('Sede A-Tercer Piso.png'),
        alt: 'Plano del bloque A piso 3 del Campus Teusaquillo',
        summary: 'Plano de distribuci\u00f3n del bloque A, tercer piso.',
        details: [],
    },
    {
        id: 'tsq-j-p2',
        shortLabel: 'Bloque J - Piso 2',
        title: 'Bloque J - Piso 2',
        imageUrl: 'https://backreservas.ucompensar.edu.co/img/tsq_j_p2.png',
        alt: 'Plano del bloque J piso 2 del Campus Teusaquillo',
        summary: 'Ubicaci\u00f3n del coworking de Talento Humano, Bienestar y Graduados.',
        details: [
            {
                label: 'Coworking - Talento Humano, Bienestar y Graduados',
                meta: '19 puestos',
                color: '#38d4c7',
            },
            {
                label: 'Sala de reunion',
                color: '#b45589',
            },
        ],
    },
];
